```{r rxs-setup-chunk-98K0Mh, echo=FALSE, results='hide'}
```

<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--                                                                       -->
<!-- Welcome to the R Extraction Script (.rxs.Rmd file) for this source!   -->
<!--                                                                       -->
<!-- You can now start extracting. If you haven't yet studied the          -->
<!-- extractor instructions, please do so first. If you're all set, good   -->
<!-- luck!                                                                 -->
<!--                                                                       -->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

```{r rxs-extraction-chunk, echo=FALSE}
##############################################################################
############################################ START: uniqueSourceIdentifier ###
##############################################################################
uniqueSourceIdentifier <- 
##############################################################################
### 
### SET UNIQUE SOURCE IDENTIFIER
### 
### A unique identifier used in this systematic review to refer to this
### source
### 
##############################################################################
    
    ""
    
##############################################################################
########################################### VALUE DESCRIPTION AND EXAMPLES ###
##############################################################################
### 
### A unique identifier to use in this systematic review. For sources
### with a DOI, this is the last part of the shortDOI as looked up
### through https://shortdoi.org (the part after the "10/"). For sources
### without a DOI (and so, without a shortDOI), this can be, for example,
### the QURID (Quasi-Unique Record Identifier) that was designated during
### the screening phase or which you can create with
### `metabefor::qurid()`.
### 
### EXAMPLES:
### 
### "g5fj"
### "qurid_7h4pksl6"
### 
##############################################################################
############################################## END: uniqueSourceIdentifier ###
##############################################################################

##############################################################################
############################################### START: extractorIdentifier ###
##############################################################################
extractorIdentifier <- 
##############################################################################
### 
### SPECIFY YOUR EXTRACTOR IDENTIFIER
### 
### An identifier unique to every extractor
### 
##############################################################################
    
    ""
    
##############################################################################
########################################### VALUE DESCRIPTION AND EXAMPLES ###
##############################################################################
### 
### Identifiers can only consist of (lower or uppercase) Latin letters
### [a-zA-Z], Arabic numerals [0-9], and underscores [_], and always have
### to start with a letter.
### 
### EXAMPLES:
### 
### "extractor_1"
### "Alex"
### 
##############################################################################
################################################# END: extractorIdentifier ###
##############################################################################


##############################################################################
##################################################### START: source (ROOT) ###
##############################################################################
rxsObject <- data.tree::Node$new('source');
currentEntity <- rxsObject;
##############################################################################

  ############################################################################
  ######################################################## START: metadata ###
  ############################################################################
  currentEntity <- currentEntity$AddChild('metadata');
  ############################################################################
  ### 
  ### METADATA
  ### 
  ### this is the parent variable for all items relating to the
  ### metadata of the tool
  ### 
  ############################################################################
      
  
    ##########################################################################
    ##################################################### START: toolTitle ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('toolTitle');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### TOOL TITLE
    ### 
    ### If the tool has a title, write it here. If there is no title,
    ### check if the tool can be identified with a project or
    ### collaborative group name or write an APA style in-text
    ### citation to identify a tool that was published with a
    ### research paper (e.g., Downs & Black (1998)).
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ####################################################### END: toolTitle ###
    ##########################################################################
  
  
    ##########################################################################
    ################################################## START: toolCitation ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('toolCitation');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### TOOL CITATION
    ### 
    ### If the paper is associated with a publication, extract the
    ### citation in APA format together with the DOI.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    #################################################### END: toolCitation ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################## START: toolCitationLink ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('toolCitationLink');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### TOOL CITATION LINK
    ### 
    ### In some cases, even if a paper is published, the tool may not
    ### be part of that publication and it has to be accessed
    ### elsewhere, for example, in a separate repository. Therefore,
    ### a citation may not be enough to find the paper. Always
    ### include a link that will point to the tool. Here, if the tool
    ### is part of the paper, add the DOI link. Otherwise, add a link
    ### that points directly to the tool.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################################ END: toolCitationLink ###
    ##########################################################################
  
  
    ##########################################################################
    ################################################## START: accessIssues ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('accessIssues');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### ACCESS ISSUES
    ### 
    ### If there are any access issues, report them here as a
    ### comment. Otherwise, leave blank.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    #################################################### END: accessIssues ###
    ##########################################################################
  
  
    ##########################################################################
    #################################################### START: accessType ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('accessType');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### ACCESS TYPE
    ### 
    ### Select whether access is open or requires paying/subscribing
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(open access, subscription)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("open access", "subscription")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ###################################################### END: accessType ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################## START: copyrightLicence ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('copyrightLicence');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### COPYRIGHT LICENCE
    ### 
    ### Check if the tool has its own licence. If yes, select the
    ### licence of the tool here. If the paper was published with an
    ### academic article and doesn’t have its own licence, select the
    ### licence that the article is published under
    ### 
    ### Select under which licence it's published; choose one of the
    ### examples: CC; BYCC; BY-NCGNU (the general public licence);
    ### Other Specify; Unclear - no licence information can be found
    ### (Write: Unclear)
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################################ END: copyrightLicence ###
    ##########################################################################
  
  
    ##########################################################################
    #################################################### START: typeOfTool ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('typeOfTool');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### TYPE OF TOOL
    ### 
    ### Does the tool identify itself with any of the following
    ### terms?
    ### 
    ### Select all that apply: Risk of Bias; Quality Assessment;
    ### Critical Appraisal; None; Other* (specify - *Select other and
    ### write the wording used to identify the tool if related to
    ### risk of bias, quality assessment or critical appraisal.)
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ###################################################### END: typeOfTool ###
    ##########################################################################
  
  
    ##########################################################################
    ######################################################## START: format ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('format');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### FORMAT
    ### 
    ### Specify the format of the tool, choose from examples and
    ### copy-paste them verbatim
    ### 
    ### Select as many as applies:
    ### A text document file with a list of items
    ### Write: Document List
    ### 
    ### A text document form that can be filled out on the computer
    ### or printed and filled out on paper
    ### Write: Fillable Form
    ### 
    ### A spreadsheet file that should be completed on the computer
    ### Write: Computer Spreadsheet
    ### 
    ### An online application or software (including a website)
    ### Write: Online Software
    ### 
    ### An offline application or software
    ### Write: Offline SoftwareOther - specify the format
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ########################################################## END: format ###
    ##########################################################################
  
  
    ##########################################################################
    ####################################################### START: support ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('support');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### SUPPORT
    ### 
    ### Is there any provision of support for authors who want to or
    ### are in the process of using the tool? For example, it could
    ### be a community mailing list, a Slack or Discord workspace, an
    ### online chat function with an adviser embedded within a
    ### website.  If this is not available in the paper,
    ### documentation or the website where the tool is, stop
    ### searching.
    ### 
    ### Pick one answer from the examples:
    ### Yes - some form of support is available - Specify
    ### Write: Support Available
    ### 
    ### No - no form of support is available
    ### Write: No Support
    ### 
    ### Unclear: Provide a comment
    ### Write: Unclear Support
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################################### END: support ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################ START: supportDescription ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('supportDescription');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### SUPPORT DESCRIPTION
    ### 
    ### Link where you found the support or describe it.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################## END: supportDescription ###
    ##########################################################################
  
      
  ############################################################################
  ############################################################################
  currentEntity <- currentEntity$parent;
  ############################################################################
  ########################################################## END: metadata ###
  ############################################################################


  ############################################################################
  ######################################################### START: content ###
  ############################################################################
  currentEntity <- currentEntity$AddChild('content');
  ############################################################################
  ### 
  ### CONTENT
  ### 
  ### parent variable for all items relating to the content of the tool
  ### 
  ############################################################################
      
  
    ##########################################################################
    ################################################# START: numberOfItems ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('numberOfItems');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### NUMBER OF ITEMS
    ### 
    ### How many items are in the tool? Some items might have long
    ### descriptions with sub-items or general categories with
    ### sub-items.
    ### 
    ### Count all items and sub-items in the tool which require an
    ### independent response, including all items relating to design,
    ### sample characteristics or metadata.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### Any valid whole number
    ### 
    ### EXAMPLES:
    ### 
    ### 30
    ### 8762
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1)));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################################### END: numberOfItems ###
    ##########################################################################
  
  
    ##########################################################################
    ######################################## START: instructionsWithinTool ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('instructionsWithinTool');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### AVAILABILITY OF ADDITIONAL INSTRUCTIONS
    ### 
    ### Explanation, elaboration, or further guides explaining what
    ### is meant by individual items
    ### 
    ### Select one of the options:
    ### No Explanation
    ### Write: No Explanation
    ### 
    ### One-Sentence Explanation
    ### Write: Brief Explanation
    ### 
    ### Longer Explanation in the Same Document
    ### Write: Detailed Explanation
    ### 
    ### Elaborated Instructions Provided in a Separate Document
    ### (e.g., a user guide)
    ### Write: Separate Guide
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(No Explanation, Brief Explanation, Detailed Explanation, Separate Guide)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("No Explanation", "Brief Explanation", "Detailed Explanation", "Separate Guide")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ########################################## END: instructionsWithinTool ###
    ##########################################################################
  
  
    ##########################################################################
    ################################################ START: intendedDesign ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('intendedDesign');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### INTENDED DESIGN
    ### 
    ### Which study designs are covered by the tool? This should be
    ### clearly stated in the tool instructions or within it.
    ### 
    ### Do not judge it from items, if you cannot find the
    ### information, state “Unclear”. Otherwise, state all mentioned
    ### designs.
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################################## END: intendedDesign ###
    ##########################################################################
  
  
    ##########################################################################
    ####################################### START: nonInterventionalDesign ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('nonInterventionalDesign');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### NON-INTERVENTIONAL DESIGN
    ### 
    ### Based on the PICOS model and the non-intervention model
    ### proposed in NIRO-SR, is the tool suitable for
    ### non-intervention research only, or is it applicable to
    ### intervention research (whether that’s because it’s
    ### specifically built for non-intervention, or because it is
    ### general enough to apply)?
    ### 
    ### Select all the options that are mentioned in the tool's
    ### items.
    ### Intervention suggested (patients instead of participants)
    ### Write: Patients Suggested
    ### 
    ### Intervention only (intervention specifically mentioned, RCTs
    ### etc)
    ### Write: Intervention Specific
    ### 
    ### Applicable to non-intervention (conceptualises dependent
    ### variables)
    ### Write: Dependent Variable Conceptualized
    ### 
    ### Applicable to non-intervention (conceptualises independent
    ### variables)
    ### Write: Independent Variable Conceptualized
    ### 
    ### Applicable to non-intervention (population / participants,
    ### not just patients)
    ### Write: Participant Focused
    ### 
    ### Applicable to non-intervention (study designs not limited to
    ### intervention research)
    ### Write: Broad Study Designs
    ### 
    ### Applicable to non-intervention (covariates or variables to
    ### control for)
    ### Write: Covariate Control
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ######################################### END: nonInterventionalDesign ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################## START: openReproScholarship ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('openReproScholarship');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### OPEN & REPRODUCIBLE SCHOLARSHIP
    ### 
    ### Select the aspects of open and reproducible research that are
    ### explicitly captured in the tool:
    ### Open Data
    ### Write: Open Data
    ### 
    ### Open access to materials used in research (e.g., new
    ### software, questionnaires)
    ### Write: Open Materials
    ### 
    ### Open source software used (e.g., GNU Octave instead of
    ### Matlab)
    ### Write: Open Software
    ### 
    ### Open analysis code
    ### Write: Open Code
    ### 
    ### Reproducibility of the methods section
    ### Write: Reproducible MethodsProtocol registration
    ### Write: Protocol registration
    ### 
    ### Sample Size Estimator
    ### Write: Sample Size Estimator
    ### 
    ### Effect Sizes Reported
    ### Write: Effect Sizes Reported
    ### 
    ### Transparency Statement
    ### Write: Transparency Statement
    ### 
    ### Reflexivity statement (on author bias)
    ### Write: Reflexivity Statement
    ### 
    ### Open access publication
    ### Write: Open Access
    ### 
    ### Preprint Archiving
    ### Write: Preprint Archive
    ### 
    ### Participatory Research (participants engaged in designing the
    ### study)
    ### Write: Participatory Research
    ### 
    ### Other
    ### Write: Other - explain
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################ END: openReproScholarship ###
    ##########################################################################
  
  
    ##########################################################################
    ########################################### START: integrityAssessment ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('integrityAssessment');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### INTEGRITY ASSESSMENT
    ### 
    ### Item based on the paper by Grey et al. (2020)
    ### 
    ### Select the aspects of integrity assessment that are
    ### explicitly captured in the tool:
    ### Funding Source
    ### Write: Funding Source
    ### 
    ### Ethics approval 
    ### Write: Ethics approval
    ### 
    ### Authorship statement
    ### Write: Authorship statement
    ### 
    ### Methodology assessment - to check if the methodology is
    ### appropriate for the aims of the study
    ### Write: Methodology assessment
    ### 
    ### Analytical approach assessment - to check for evidence of
    ### inappropriate data handling, missing data or inappropriate
    ### analyses 
    ### Write: Analysis assessment
    ### 
    ### Data errors - to check if the reported data or results are
    ### clearly implausible (for example, using the statcheck app,
    ### http://statcheck.io/) 
    ### Write: Data errors
    ### 
    ### Conflict of interest statement
    ### Write: COI Statement
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################# END: integrityAssessment ###
    ##########################################################################
  
  
    ##########################################################################
    ##################################### START: validityAssessmentContent ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('validityAssessmentContent');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### VALIDITY ASSESSMENT CONTENT - NON-INTERVENTION RESEARCH
    ### ELEMENTS
    ### 
    ### Item based on the paper by Schiavone et al. (2023) Does the
    ### tool require the researcher to evaluate the following types
    ### of validity?
    ### 
    ### Select all examples that apply:
    ### Construct validity - Operationalisation/rationale of the
    ### dependent and independent variables
    ### Write: Construct Validity
    ### 
    ### Internal validity - Acknowledgment and/or measurement of
    ### confounding variables
    ### Write: Confounding Acknowledgment
    ### 
    ### Internal validity - Inclusion and report of baseline measures
    ### Write: Baseline Measures
    ### 
    ### Internal validity - Within-subject order effects accounted
    ### for
    ### Write: Order Effects
    ### 
    ### Internal validity - Sufficiently controlled comparison group
    ### or condition
    ### Write: Controlled Group
    ### 
    ### External validity - Detailed description of the sample and
    ### limits to generalisability
    ### Write: Sample Description
    ### 
    ### External validity - Attrition rate reported
    ### Write: Attrition Rate
    ### 
    ### External validity - The characteristics of participants who
    ### were excluded or did not complete the study reported
    ### Write: Exclusion Details
    ### 
    ### Statistical validity - Conducted data quality assessment or
    ### assessment of the quality of participant responses
    ### Write: Data Quality
    ### 
    ### Statistical validity - Rationale for the appropriateness of
    ### statistical analyses provided
    ### Write: Statistical RationaleOther - Specify
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ####################################### END: validityAssessmentContent ###
    ##########################################################################
  
  
    ##########################################################################
    ################################################### START: ratingStyle ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('ratingStyle');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### RATING/SCORING STYLE
    ### 
    ### What is the assessment system used to understand the risk of
    ### bias/quality in individual papers?
    ### 
    ### Select as many as apply:
    ### Binary - Specify which type, e.g., yes/no, low risk/high risk
    ### Write: Binary Type
    ### 
    ### Categorical - Specify how many categories and what they are,
    ### e.g. ‘good’, ‘fair’, ‘poor’ or ‘very poor’
    ### Write: Categorical Type
    ### 
    ### Points system - Specify the range of points allocated per
    ### item as well as the possible total score
    ### Write: Points System
    ### 
    ### Other - Describe the assessment system
    ### Write: Other System None
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ##################################################### END: ratingStyle ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################### START: ratingStyleSpex ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('ratingStyleSpex');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### RATING/SCORING STYLE SPECIFICATION
    ### 
    ### Here specify the assessment system used per individual item.
    ### E.g., yes/no, low risk/high risk; Specify how many categories
    ### and what they are, e.g. ‘good’, ‘fair’, ‘poor’ or ‘very
    ### poor’; Specify the range of points allocated per item as well
    ### as the possible total score; Describe the assessment system
    ### if other
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ################################################# END: ratingStyleSpex ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################# START: ratingInstruction ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('ratingInstruction');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### RATING/SCORING INSTRUCTION
    ### 
    ### Does the tool clearly explain how to use the assessment
    ### system? How are the categories/scores assigned?
    ### 
    ### Select one of the following:
    ### Yes - Very clear instructions with specific examples per item
    ### (e.g. “high risk” category in an item for studies with no
    ### control group or condition)
    ### Write: Clear with Examples
    ### 
    ### Yes - Clear instructions but apply to the whole tool with no
    ### item-specific examples (e.g. mark “No” for all items that do
    ### not reflect what was done in the paper”)
    ### Write: Clear General
    ### 
    ### No - There are instructions for using the assessment system
    ### but they are unclear and leave room for interpretation
    ### Write: Unclear Instructions
    ### 
    ### No - There are no instructions for the assessment system
    ### Write: No Instructions
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(Clear with Examples, Clear General, Unclear Instructions, No Instructions)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("Clear with Examples", "Clear General", "Unclear Instructions", "No Instructions")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################### END: ratingInstruction ###
    ##########################################################################
  
  
    ##########################################################################
    ######################################## START: overallAssessmentScore ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('overallAssessmentScore');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### OVERALL ASSESSMENT RESULT/SCORE
    ### 
    ### Does the tool provide a way to synthesise individual
    ### ratings/scores to arrive at an overall result?
    ### 
    ### Select as many as apply:
    ### Binary
    ### Write: Binary Type
    ### 
    ### Categorical
    ### Write: Categorical Type
    ### 
    ### Points system
    ### Write: Points System
    ### 
    ### Other
    ### Write: Other System
    ### 
    ### No - The tool does not provide a way to synthesise the
    ### individual ratings/scores to arrivae at an overall result
    ### Write: No
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ########################################## END: overallAssessmentScore ###
    ##########################################################################
  
  
    ##########################################################################
    #################################### START: overallAssessmentScoreSpex ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('overallAssessmentScoreSpex');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### OVERALL ASSESSMENT RESULT/SCORE SPECIFICATION
    ### 
    ### Here specify the overall assessment system. Specify which
    ### type, e.g., yes/no, low risk/high risk; Specify how many
    ### categories and what they are, e.g. ‘good’, ‘fair’, ‘poor’ or
    ### ‘very poor’; Specify the range of points allocated per item
    ### as well as the possible total score; Describe the assessment
    ### system if other
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A single character value
    ### 
    ### EXAMPLES:
    ### 
    ### "example"
    ### "another example"
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ###################################### END: overallAssessmentScoreSpex ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################ START: practicalUseByItem ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('practicalUseByItem');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### PRACTICAL USE BY ITEM
    ### 
    ### Is there any guidance for how positive and negative
    ### ratings/scores for individual items should impact the
    ### systematic review process?
    ### 
    ### Select one:
    ### Yes, the tool provides guidance for practical use of
    ### individual ratings/scores in the systematic review
    ### Write: Guidance Provided
    ### 
    ### No, the tool does not include guidance for practical use of
    ### individual ratings/scores in the systematic review
    ### Write: No Guidance
    ### 
    ### Unclear - some guidance is provided but it is not clear
    ### Write: Unclear Guidance
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(Guidance Provided, No Guidance, Unclear Guidance)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("Guidance Provided", "No Guidance", "Unclear Guidance")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################## END: practicalUseByItem ###
    ##########################################################################
  
  
    ##########################################################################
    ############################################ START: practiceUseOverall ###
    ##########################################################################
    currentEntity <- currentEntity$AddChild('practiceUseOverall');
    currentEntity[['value']] <-
    ##########################################################################
    ### 
    ### PRACTICAL USE OVERALL
    ### 
    ### Is there any guidance for how the overall outcome of the
    ### assessment should be used in practice? How should the overall
    ### outcome of the assessment be interpreted as a whole?
    ### 
    ### Select one:
    ### Yes, the tool provides guidance for the overall outcome
    ### interpretation with implications for the systematic review
    ### Write: Guidance with Implications
    ### 
    ### Yes, the tool provides guidance for the overall outcome
    ### interpretation but no practical implications
    ### Write: Guidance, No Implications
    ### 
    ### No, the tool does not mention the overall outcome
    ### interpretation
    ### Write: No Outcome Guidance
    ### 
    ### Unclear - guidance is provided but it is not clear
    ### Write: Unclear Guidance
    ### 
    ##########################################################################
        
        NA
        
    ##########################################################################
    ####################################### VALUE DESCRIPTION AND EXAMPLES ###
    ##########################################################################
    ### 
    ### A string that has to exactly match one of the values
    ### specified in the "values" column of the Coding sheet
    ### 
    ### EXAMPLE:
    ### 
    ### c(Guidance with Implications, Guidance, No Implications, No Outcome Guidance, Unclear Guidance)
    ### 
    ##########################################################################
    currentEntity[['validation']] <- expression(all(is.na(VALUE)) || (VALUE %in% c("Guidance with Implications", "Guidance, No Implications", "No Outcome Guidance", "Unclear Guidance")));
    currentEntity <- currentEntity$parent;
    ##########################################################################
    ############################################## END: practiceUseOverall ###
    ##########################################################################
  
      
  ############################################################################
  ############################################################################
  currentEntity <- currentEntity$parent;
  ############################################################################
  ########################################################### END: content ###
  ############################################################################

    
##############################################################################
####################################################### END: source (ROOT) ###
##############################################################################
class(rxsObject) <- c('rxs', 'rxsObject', class(rxsObject));
rxsObject$rxsMetadata <- list(rxsVersion='0.3.0', moduleId=NULL, id=uniqueSourceIdentifier, extractorId=extractorIdentifier);
##############################################################################
##############################################################################
##############################################################################
```

<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--                                                                       -->
<!-- Well done! You are now done extracting this source. Great job!!!      -->
<!--                                                                       -->
<!-- Now, please knit the R Extraction Script into an HTML file and        -->
<!-- carefully check whether you entered everything correctly, since it    -->
<!-- will cost much less time to correct any errors, now that you still    -->
<!-- have this source in your mind, than later on when you'll have to      -->
<!-- dive into it all over.                                                -->
<!--                                                                       -->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->












```{r rxs-template-specification-chunk-NZaVsT, echo=FALSE, results='hide'}
```

```{r rxs-validation-chunk-LIMVoC, results='asis'}
metabefor::heading('Validation results', headingLevel = 1);
metabefor::rxs_validation(
  rxsObject,
  stopOnFailure = FALSE,
  rxsTemplateSpec = rxsTemplateSpec);
cat(paste0('- ', rxsObject$validationLog), sep='\n');
```

```{r rxs-show-extracted-data-chunk-tQPdEK}
if ((!(exists('parsingMultipleRxsFiles'))) || (!parsingMultipleRxsFiles)) {  metabefor::rxs_partial(rxsObject); }
```

```{r rxs-setup-chunk-98K0Mh, include=FALSE, messages=FALSE}
### First check for (and perhaps install) metabefor
if (!(requireNamespace('metabefor', quietly = TRUE))) {
  install.packages('metabefor', repos='http://cran.rstudio.com');
}

### Settings
knitr::opts_chunk$set(echo = FALSE);     ### Suppress R command printing
knitr::opts_chunk$set(comment = NA);     ### Suppress output prefix
```

---
title: "`r paste0('Rxs for \'', uniqueSourceIdentifier, '\' (', metabefor::knittedFileSansExt(), ')')`"
author: "`r paste0('Extractor: ', extractorIdentifier)`"
date: "`r format(Sys.time(), '%Y-%m-%d at %H:%M:%S %Z (UTC%z)')`"
output:
  html_document:
    embed-resources: true
    toc: false
params:
  rxsVersion: "0.3.0"
  rxsRootName: "source"
  rxsObjectName: "rxsObject"
editor_options:
  chunk_output_type: console
---


<!-- Here, the original Rxs template specification is included. ~~~~~~~~~~~-->

```{r rxs-template-specification-chunk-NZaVsT, echo=FALSE}

rxsTemplateSpec <- 
  list(entities = structure(list(title = c("Metadata", "Tool Title", 
  "Tool Citation", "Tool Citation Link", "Access Issues", "Access Type", 
  "Copyright Licence", "Type of Tool", "Format", "Support", "Support description", 
  "Content", "Number of Items", "Availability of additional instructions", 
  "Intended Design", "Non-Interventional Design", "Open & Reproducible Scholarship", 
  "Integrity Assessment", "Validity Assessment Content - Non-intervention Research Elements", 
  "Rating/Scoring Style", "Rating/Scoring Style Specification", 
  "Rating/Scoring Instruction", "Overall Assessment Result/Score", 
  "Overall Assessment Result/Score Specification", "Practical Use by Item", 
  "Practical Use Overall"), description = c("this is the parent variable for all items relating to the metadata of the tool", 
  NA, "If the paper is associated with a publication, extract the citation in APA format together with the DOI.", 
  "In some cases, even if a paper is published, the tool may not be part of that publication and it has to be accessed elsewhere, for example, in a separate repository. Therefore, a citation may not be enough to find the paper. Always include a link that will point to the tool. Here, if the tool is part of the paper, add the DOI link. Otherwise, add a link that points directly to the tool.", 
  NA, NA, "Check if the tool has its own licence. If yes, select the licence of the tool here. If the paper was published with an academic article and doesn’t have its own licence, select the licence that the article is published under", 
  "Does the tool identify itself with any of the following terms?", 
  "Specify the format of the tool, choose from examples and copy-paste them verbatim", 
  "Is there any provision of support for authors who want to or are in the process of using the tool? For example, it could be a community mailing list, a Slack or Discord workspace, an online chat function with an adviser embedded within a website.  If this is not available in the paper, documentation or the website where the tool is, stop searching.", 
  "Link where you found the support or describe it.", "parent variable for all items relating to the content of the tool", 
  "How many items are in the tool? Some items might have long descriptions with sub-items or general categories with sub-items.", 
  "Explanation, elaboration, or further guides explaining what is meant by individual items", 
  "Which study designs are covered by the tool? This should be clearly stated in the tool instructions or within it.", 
  "Based on the PICOS model and the non-intervention model proposed in NIRO-SR, is the tool suitable for non-intervention research only, or is it applicable to intervention research (whether that’s because it’s specifically built for non-intervention, or because it is general enough to apply)?", 
  NA, "Item based on the paper by Grey et al. (2020)", "Item based on the paper by Schiavone et al. (2023) Does the tool require the researcher to evaluate the following types of validity?", 
  "What is the assessment system used to understand the risk of bias/quality in individual papers?", 
  NA, "Does the tool clearly explain how to use the assessment system? How are the categories/scores assigned?", 
  "Does the tool provide a way to synthesise individual ratings/scores to arrive at an overall result?", 
  NA, "Is there any guidance for how positive and negative ratings/scores for individual items should impact the systematic review process?", 
  "Is there any guidance for how the overall outcome of the assessment should be used in practice? How should the overall outcome of the assessment be interpreted as a whole?"
  ), instructions = c(NA, "If the tool has a title, write it here. If there is no title, check if the tool can be identified with a project or collaborative group name or write an APA style in-text citation to identify a tool that was published with a research paper (e.g., Downs & Black (1998)).", 
  NA, NA, "If there are any access issues, report them here as a comment. Otherwise, leave blank.", 
  "Select whether access is open or requires paying/subscribing", 
  "Select under which licence it's published; choose one of the examples: CC; BYCC; BY-NCGNU (the general public licence); Other Specify; Unclear - no licence information can be found (Write: Unclear)", 
  "Select all that apply: Risk of Bias; Quality Assessment; Critical Appraisal; None; Other* (specify - *Select other and write the wording used to identify the tool if related to risk of bias, quality assessment or critical appraisal.)", 
  "Select as many as applies: \n    A text document file with a list of items\n        Write: Document List\n\n    A text document form that can be filled out on the computer or printed and filled out on paper\n        Write: Fillable Form\n\n    A spreadsheet file that should be completed on the computer\n        Write: Computer Spreadsheet\n\n    An online application or software (including a website)\n        Write: Online Software\n\n    An offline application or software\n       Write: Offline SoftwareOther - specify the format", 
  "Pick one answer from the examples:\n    Yes - some form of support is available - Specify\n       Write: Support Available\n\n    No - no form of support is available\n        Write: No Support\n\n    Unclear: Provide a comment\n        Write: Unclear Support", 
  NA, NA, "Count all items and sub-items in the tool which require an independent response, including all items relating to design, sample characteristics or metadata.", 
  "Select one of the options:\n    No Explanation\n        Write: No Explanation\n\n    One-Sentence Explanation\n       Write: Brief Explanation\n\n    Longer Explanation in the Same Document\n        Write: Detailed Explanation\n\n    Elaborated Instructions Provided in a Separate Document (e.g., a user guide)\n        Write: Separate Guide", 
  "Do not judge it from items, if you cannot find the information, state “Unclear”. Otherwise, state all mentioned designs.", 
  "Select all the options that are mentioned in the tool's items.\n    Intervention suggested (patients instead of participants)\n       Write: Patients Suggested\n\n    Intervention only (intervention specifically mentioned, RCTs etc)\n       Write: Intervention Specific\n\n    Applicable to non-intervention (conceptualises dependent variables)\n       Write: Dependent Variable Conceptualized\n\n    Applicable to non-intervention (conceptualises independent variables)\n       Write: Independent Variable Conceptualized\n\n     Applicable to non-intervention (population / participants, not just patients)\n       Write: Participant Focused\n\n     Applicable to non-intervention (study designs not limited to intervention research)\n       Write: Broad Study Designs\n\n     Applicable to non-intervention (covariates or variables to control for)\n       Write: Covariate Control", 
  "Select the aspects of open and reproducible research that are explicitly captured in the tool:\n   Open Data\n       Write: Open Data\n\n    Open access to materials used in research (e.g., new software, questionnaires)\n        Write: Open Materials\n\n    Open source software used (e.g., GNU Octave instead of Matlab)\n        Write: Open Software\n\n    Open analysis code\n        Write: Open Code\n\n    Reproducibility of the methods section\n        Write: Reproducible MethodsProtocol registration\n        Write: Protocol registration\n\n    Sample Size Estimator\n       Write: Sample Size Estimator\n\n    Effect Sizes Reported\n       Write: Effect Sizes Reported\n\n    Transparency Statement\n       Write: Transparency Statement\n\n    Reflexivity statement (on author bias)\n        Write: Reflexivity Statement\n\n    Open access publication\n        Write: Open Access\n\n    Preprint Archiving\n        Write: Preprint Archive\n    \n    Participatory Research (participants engaged in designing the study)\n        Write: Participatory Research\n\n    Other\n       Write: Other - explain", 
  "Select the aspects of integrity assessment that are explicitly captured in the tool:\n      Funding Source\n        Write: Funding Source\n\n      Ethics approval \n        Write: Ethics approval\n\n      Authorship statement\n        Write: Authorship statement\n\n      Methodology assessment - to check if the methodology is appropriate for the aims of the study\n        Write: Methodology assessment\n\n      Analytical approach assessment - to check for evidence of inappropriate data handling, missing data or inappropriate analyses \n        Write: Analysis assessment\n\n      Data errors - to check if the reported data or results are clearly implausible (for example, using the statcheck app, http://statcheck.io/) \n        Write: Data errors\n\n    Conflict of interest statement\n        Write: COI Statement", 
  "Select all examples that apply:\n    Construct validity - Operationalisation/rationale of the dependent and independent variables\n        Write: Construct Validity\n\n    Internal validity - Acknowledgment and/or measurement of confounding variables\n        Write: Confounding Acknowledgment\n\n    Internal validity - Inclusion and report of baseline measures\n        Write: Baseline Measures\n\n    Internal validity - Within-subject order effects accounted for\n        Write: Order Effects\n\n    Internal validity - Sufficiently controlled comparison group or condition\n        Write: Controlled Group\n\n    External validity - Detailed description of the sample and limits to generalisability\n        Write: Sample Description\n\n    External validity - Attrition rate reported\n        Write: Attrition Rate\n\n    External validity - The characteristics of participants who were excluded or did not complete the study reported\n        Write: Exclusion Details\n\n    Statistical validity - Conducted data quality assessment or assessment of the quality of participant responses\n        Write: Data Quality\n\n    Statistical validity - Rationale for the appropriateness of statistical analyses provided\n       Write: Statistical RationaleOther - Specify", 
  "Select as many as apply:\n    Binary - Specify which type, e.g., yes/no, low risk/high risk\n        Write: Binary Type\n\n    Categorical - Specify how many categories and what they are, e.g. ‘good’, ‘fair’, ‘poor’ or ‘very poor’\n        Write: Categorical Type\n\n    Points system - Specify the range of points allocated per item as well as the possible total score\n        Write: Points System\n\n    Other - Describe the assessment system\n        Write: Other System  None", 
  "Here specify the assessment system used per individual item. E.g., yes/no, low risk/high risk; Specify how many categories and what they are, e.g. ‘good’, ‘fair’, ‘poor’ or ‘very poor’; Specify the range of points allocated per item as well as the possible total score; Describe the assessment system if other", 
  "Select one of the following:\n    Yes - Very clear instructions with specific examples per item (e.g. “high risk” category in an item for studies with no control group or condition)\n        Write: Clear with Examples\n\n    Yes - Clear instructions but apply to the whole tool with no item-specific examples (e.g. mark “No” for all items that do not reflect what was done in the paper”)\n        Write: Clear General\n\n    No - There are instructions for using the assessment system but they are unclear and leave room for interpretation\n        Write: Unclear Instructions\n\n    No - There are no instructions for the assessment system\n        Write: No Instructions", 
  "Select as many as apply:\n    Binary \n        Write: Binary Type\n\n    Categorical \n        Write: Categorical Type\n\n    Points system \n        Write: Points System\n\n    Other \n        Write: Other System\n\n    No - The tool does not provide a way to synthesise the individual ratings/scores to arrivae at an overall result\n        Write: No", 
  "Here specify the overall assessment system. Specify which type, e.g., yes/no, low risk/high risk; Specify how many categories and what they are, e.g. ‘good’, ‘fair’, ‘poor’ or ‘very poor’; Specify the range of points allocated per item as well as the possible total score; Describe the assessment system if other", 
  "Select one:\n    Yes, the tool provides guidance for practical use of individual ratings/scores in the systematic review\n        Write: Guidance Provided\n\n    No, the tool does not include guidance for practical use of individual ratings/scores in the systematic review\n        Write: No Guidance\n\n    Unclear - some guidance is provided but it is not clear\n        Write: Unclear Guidance", 
  "Select one:\n    Yes, the tool provides guidance for the overall outcome interpretation with implications for the systematic review\n        Write: Guidance with Implications\n\n    Yes, the tool provides guidance for the overall outcome interpretation but no practical implications\n        Write: Guidance, No Implications\n\n    No, the tool does not mention the overall outcome interpretation\n        Write: No Outcome Guidance\n\n    Unclear - guidance is provided but it is not clear\n        Write: Unclear Guidance"
  ), identifier = c("metadata", "toolTitle", "toolCitation", "toolCitationLink", 
  "accessIssues", "accessType", "copyrightLicence", "typeOfTool", 
  "format", "support", "supportDescription", "content", "numberOfItems", 
  "instructionsWithinTool", "intendedDesign", "nonInterventionalDesign", 
  "openReproScholarship", "integrityAssessment", "validityAssessmentContent", 
  "ratingStyle", "ratingStyleSpex", "ratingInstruction", "overallAssessmentScore", 
  "overallAssessmentScoreSpex", "practicalUseByItem", "practiceUseOverall"
  ), valueTemplate = c(NA, "string", "string", "string", "string", 
  "categorical", "string", "string", "string", "string", "string", 
  NA, "integer", "categorical", "string", "string", "string", "string", 
  "string", "string", "string", "categorical", "string", "string", 
  "categorical", "categorical"), validValues = c(NA, NA, NA, NA, 
  NA, "open access || subscription", NA, NA, NA, NA, NA, NA, NA, 
  "No Explanation || Brief Explanation || Detailed Explanation || Separate Guide", 
  NA, NA, NA, NA, NA, NA, NA, "Clear with Examples || Clear General || Unclear Instructions || No Instructions", 
  NA, NA, "Guidance Provided || No Guidance || Unclear Guidance", 
  "Guidance with Implications || Guidance, No Implications || No Outcome Guidance || Unclear Guidance"
  ), default = c(NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_), examples = c(NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_, NA_character_, 
  NA_character_, NA_character_, NA_character_, NA_character_), 
      parent = c(NA, "metadata", "metadata", "metadata", "metadata", 
      "metadata", "metadata", "metadata", "metadata", "metadata", 
      "metadata", NA, "content", "content", "content", "content", 
      "content", "content", "content", "content", "content", "content", 
      "content", "content", "content", "content"), ...10 = c(NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_), entityRef = c(NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_
      ), fieldRef = c(NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_), owner = c(NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_), list = c(NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_), collapsing = c(NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_), repeating = c(NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_
      ), recurring = c(NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_), recursing = c(NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_), identifying = c(NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_, 
      NA_character_, NA_character_, NA_character_, NA_character_
      )), row.names = c(NA, -26L), class = "data.frame"), valueTemplates = structure(list(
      identifier = c("numeric", "numeric.multi", "integer", "integer.multi", 
      "integer.length4.multi", "string", "string.multi", "countrycode", 
      "categorical", "categorical.multi", "generalPresence", "string.mandatory", 
      "string.entityRef.mandatory", "string.entityRef.optional", 
      "string.fieldRef.optional", "matrix.crosstab", "string.identifier"
      ), description = c("Any valid number", "A vector of valid numbers", 
      "Any valid whole number", "A vector of integers (i.e. one or more whole numbers)", 
      "A numeric vector of years, where each year must have exactly 4 digits.", 
      "A single character value", "A character vector (i.e. one or more strings)", 
      "A character vector of the ISO 3166-1 alpha-2 country code(s)", 
      "A string that has to exactly match one of the values specified in the \"values\" column of the Coding sheet", 
      "A vector of strings where each element has to exactly match one of the values specified in the \"values\" column of the Coding sheet", 
      "Whether the thing being coded was present or not.", "A single character value that cannot be omitted", 
      "A string that specifies another entity and which MUST be provided", 
      "A string that specifies another entity (can be missing, i.e. NA)", 
      "A string that specifies another field in another entity (can be missing, i.e. NA).", 
      "A table with frequencies; variable 1 in columns, variable 2 in rows; always work from absence/negative/less (left, top) to presence/positive/more (right, bottom)", 
      "A single character value that is used as an identifier and so is always mandatory and can only contain a-z, A-Z, 0-9, and underscores, and must start with a letter."
      ), validValues = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
      "\"Unknown\" || \"Present\" || \"Absent\"", NA, NA, NA, NA, 
      NA, NA), default = c("NA", "NA", "NA", "NA", "NA", "NA", 
      "\"\"", "NA", "NA", "NA", "NA", "\"Enter name here (mandatory)\"", 
      "\"enter <<entityRef>> here\"", "NA", "NA", "NA", "NA"), 
      examples = c("2.3 || 643.2", "c(23.43, 62) || 52.2 || c(76, 12.56, 42)", 
      "30 || 8762", "c(23, 62) || 52 || c(76, 12, 42)", "2001 || c(2001, 2002)", 
      "\"example\" || \"another example\"", "c(\"first value\", \"second value\")", 
      "\"NL\" || c(\"NL\", \"BE\")", "<<validValues>>", "<<validValues>>", 
      "<<validValues>>", "\"example\" || \"another example\"", 
      "<no example>", "<no example>", "<no example>", "rawTable(10, 5, 15, 10) || rawTable(31, 87, 21, 54, 25, 32, ncol=3)", 
      "\"example1\" || \"another_identifier_example\" || \"finalExample\""
      ), validation = c("all(is.na(VALUE)) || (is.numeric(VALUE) && (length(VALUE) == 1))", 
      "all(is.na(VALUE)) || (is.numeric(VALUE))", "all(is.na(VALUE)) || (is.numeric(VALUE) && (VALUE%%1==0) && (length(VALUE) == 1))", 
      "all(is.na(VALUE)) || (is.numeric(VALUE) && all(VALUE%%1==0))", 
      "all(is.na(VALUE)) || (is.numeric(VALUE) && all(nchar(VALUE)==4))", 
      "all(is.na(VALUE)) || (is.character(VALUE) && length(VALUE) == 1)", 
      "all(is.na(VALUE)) || (is.character(VALUE))", "all(is.na(VALUE)) || (VALUE %in% countryCodeList())", 
      "all(is.na(VALUE)) || (VALUE %in% <<validValues>>)", "all(is.na(VALUE)) || all(VALUE %in% <<validValues>>)", 
      "all(is.na(VALUE)) || (VALUE %in% <<validValues>>)", "all(is.na(VALUE)) && !is.null(VALUE) && (nchar(VALUE) > 0)", 
      "rxs_findEntity(node, \"<<entityRef>>\", VALUE)", "all(is.na(VALUE)) || (!is.na(VALUE) && rxs_findEntity(node, \"<<entityRef>>\", VALUE))", 
      "all(is.na(VALUE)) || (!is.na(VALUE) && rxs_findFieldInEntity(node, \"<<fieldRef>>\", VALUE))", 
      "all(is.na(VALUE)) || (class(VALUE) == \"matrix\")", "grepl(\"[a-zA-Z][a-zA-Z0-9_]*\", VALUE)"
      ), error = c("NAME is not numeric, or contains more than one value.", 
      "NAME is not a numeric vector.", "Error about NAME here.", 
      "Error about NAME here.", "Error about NAME here.", "Error about NAME here.", 
      "Error about NAME here.", "Error about NAME here.", "Error about NAME here.", 
      "Error about NAME here.", "Error about NAME here.", "This string (character value) must be entered.", 
      "Enter a valid reference to another entity - or remove unused entities.", 
      "Error about NAME here.", "Error about NAME here.", "Error about NAME here.", 
      "The identifier provided as NAME contains invalid characters (i.e. something that is not a-z, A-Z, 0-9, or _) or does not start with a letter."
      )), row.names = c(NA, -17L), class = "data.frame"), definitions = structure(list(
      term = "Example Term", definition = "Example definition of the term."), row.names = c(NA, 
  -1L), class = "data.frame"), instructionSheet = structure(list(
      heading = character(0), description = character(0)), row.names = integer(0), class = "data.frame"), 
      textsSheet = structure(list(textIdentifier = c("openingRemarks", 
      "closingRemarks", "extractionOverview_list_intro", "extractionOverview_compact_intro"
      ), content = c("Welcome to the R Extraction Script (.rxs.Rmd file) for this source!\n\nYou can now start extracting. If you haven't yet studied the extractor instructions, please do so first. If you're all set, good luck!", 
      "Well done! You are now done extracting this source. Great job!!!\r\n\r\nNow, please knit the R Extraction Script into an HTML file and carefully check whether you entered everything correctly, since it will cost much less time to correct any errors, now that you still have this source in your mind, than later on when you'll have to dive into it all over.", 
      "This is an overview of the entities to extract, their titles and descriptions, and other details that will become part of the extraction script template that will be used for the actual extraction.", 
      "This is an overview of the entities to extract, their titles and descriptions, and other details that will become part of the extraction script template that will be used for the actual extraction."
      )), row.names = c(NA, -4L), class = "data.frame"), textsList = list(
          openingRemarks = c(content = "Welcome to the R Extraction Script (.rxs.Rmd file) for this source!\n\nYou can now start extracting. If you haven't yet studied the extractor instructions, please do so first. If you're all set, good luck!"), 
          closingRemarks = c(content = "Well done! You are now done extracting this source. Great job!!!\r\n\r\nNow, please knit the R Extraction Script into an HTML file and carefully check whether you entered everything correctly, since it will cost much less time to correct any errors, now that you still have this source in your mind, than later on when you'll have to dive into it all over."), 
          extractionOverview_list_intro = c(content = "This is an overview of the entities to extract, their titles and descriptions, and other details that will become part of the extraction script template that will be used for the actual extraction."), 
          extractionOverview_compact_intro = c(content = "This is an overview of the entities to extract, their titles and descriptions, and other details that will become part of the extraction script template that will be used for the actual extraction.")), 
      errorOnFailingValidation = FALSE, rxsRootName = "source", 
      yamlMetadata = NULL)

```

